### ISSUE TITLE
"File Not Found" after configuring only wifi 

### ISSUE THREAD

**Issue by rrozema** [akamming/esp_domoticz_opentherm_handler#2]
I connected to the wifi AP on my phone (http://192.168.4.1) and only configured the wifi connection -with the idea to continue configuring on my pc-. However after opening the websever (via the ip address assigned in the new network: http://192.168.128.77), I got an error message:
"
File Not Found

URI: /
Method: GET
Arguments 0
"

**Comment by rrozema** [comment]
Serial output:

*wm:connectTimeout not set, ESP waitForConnectResult... 
*wm:AutoConnect: SUCCESS 
*wm:STA IP Address: 192.168.128.77
MDNS responder started
IP address: 192.168.128.77
Opentherm Helper is waiting for commands
.Opentherm Error: Response timeout

....

.Opentherm Error: Response timeout
serveFile(): /

E.Opentherm Error: Response timeout

**Comment by akamming** [comment]
You have 2 issues
1. You did not upload the sketch data as described in the instructions , Hence the missing file
2. Ot is not properly connected, hence the response timeout

**Comment by rrozema** [comment]
2 I was aware of, 1 i will read and correct now.

**Comment by rrozema** [comment]
I do not get the menu entry Tools / ESP8266 Sketch Data Upload after installing the ESP8266FS tool in C:\Users\richard\Documents\Arduino\tools\ESP8266FS\tool and restarting Arduino IDE as described. Do you have any hints for me? (+ Is the Domoticz forum private message a better way to communicate than via this issue or do we continue here to help others?)

**Comment by akamming** [comment]
This is more arduino stuff. So put it in arduino forums

just see there is a new 2.0 arduino which does not support. If you install the legacy version it should work. That one you can also download on arduino software page

i’m Gonna close the issue. This is not an issue in the firmware. ASK indeed help om arduino or domoticz forums
